### PR TITLE
Fixed Automatic Google Sign In

### LINKED ISSUE #10: Automatic Google sign in
**Describe the bug**
When we sign in using Google for the second or subsequent times after log out, the app does not give any option to select accounts, rather it automatically uses the last used google account.

**To Reproduce**
1. Sign in using Google.
2. Log out.
3. Try logging in again using google.
4. The user is automatically logged in without any option to select an account.

**GIF**
Here is the link
https://gifyu.com/image/9eah

**Expected behavior**
Every time the user should have the option to select which account to use to log in.

**Smartphone (please complete the following information):**
 - Device: Redmi 4
 - OS: Android Nougat

### PR DESCRIPTION
**Pull request by prajwal72**
CommonFunctions.java: added GoogleSignInClient sign out

App didn't used to ask for account after first sign in

Closes https://github.com/oss2019/instigo-android/issues/10

### CODE REVIEW

**Comment by prajwal72** [comment]
@sonusourav

File: app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java [hunk 1]
```diff
@@ -86,6 +92,18 @@ public static boolean navigationItemSelect(MenuItem item, final Activity activit
...
+                        .build();
+                GoogleSignInClient googleSignInClient = GoogleSignIn.getClient(activity, gso);
+                googleSignInClient.signOut().addOnCompleteListener(new OnCompleteListener<Void>() {
+                    @Override
+                    public void onComplete(@NonNull Task<Void> task) {
+
+                    }
+                });
+                
                 Toast.makeText(activity.getApplicationContext(), "User successfully logged out.", Toast.LENGTH_SHORT).show();
```
Comment (sonusourav) [inline app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java]: How about moving the Toast and intent inside onComplete()? That way the addition will make more sense otherwise, chances are there that there might be an error in onComplete and still the intent and Toast may be executed. After committing, squash your commits.

Comment (prajwal72) [reply app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java]: Review @sonusourav

File: app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java [hunk 2]
```diff
@@ -83,13 +91,34 @@ public static boolean navigationItemSelect(MenuItem item, final Activity activit
...
 
-                Toast.makeText(activity.getApplicationContext(), "User successfully logged out.", Toast.LENGTH_SHORT).show();
-                activity.startActivity(new Intent().setClass(activity, LoginActivity.class));
+                FirebaseAuth loginAuth=FirebaseAuth.getInstance();
+                GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
+                        .requestIdToken(activity.getResources().getString(R.string.default_web_client_id))
+                        .requestEmail()
+                        .build();
+                GoogleSignInClient googleSignInClient = GoogleSignIn.getClient(activity, gso);
+
```
Comment (sonusourav) [inline app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java:103]: If part is always equal to false, you can remove that. And put loginAuth.signOut() just after you defined Firebase Auth

Comment (prajwal72) [reply app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java:103]: googleSignInClient will be null when the user is signed in with email, that block is intended to sign out such users and the else block is intended to sign out users who login through Goggle Sign In

Comment (sonusourav) [reply app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java:103]: Cool, and why isn't loginAuth.signOut() in else part also?

Comment (prajwal72) [reply app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java:103]: loginAuth.signOut() is needed for signing out from email. For google sign in, googleSignInClient is sufficient.

Comment (sonusourav) [reply app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java:103]: Are you sure? Checkout this https://stackoverflow.com/a/38707954/8616229

Comment (prajwal72) [reply app/src/main/java/com/iitdh/sonusourav/instigo/Utils/CommonFunctions.java:103]: Sorry! My mistake. I was reading the Google sign in docs instead of the Firebase docs.
