### PR TITLE
progress bar fix on google sign in cancelled.

### LINKED ISSUE #4: Progress dialog displayed on backpress while google signin
**Describe the bug**
When the dialog builder for selecting email accounts in google sign pops up and user presses back button then dialog progress bar gets displayed.

**To Reproduce**
1. Go to the login screen
2. Press Google sign in button
3. Press back button and observe progress dialog is displayed

**Expected behavior**
The progress dialog should not be displayed.

**Screenshots**
progress_dialog_in_google_signin

**Smartphone (please complete the following information):**
 - Device: Redmi 4
 - OS: Android Nougat

### PR DESCRIPTION
**Pull request by codersanjeev**
Fixes #4 
ezgif com-optimize

### CODE REVIEW

**Comment by codersanjeev** [comment]
review @sonusourav

File: app/src/main/java/com/iitdh/sonusourav/instigo/Account/LoginActivity.java [hunk 1]
```diff
@@ -315,9 +316,16 @@ public void onActivityResult(int requestCode, int resultCode, Intent data) {
                         firebaseAuthWithGoogle(account);
                     }
                 } catch (ApiException e) {
-                    Toast.makeText(LoginActivity.this, e.getMessage(), Toast.LENGTH_SHORT).show();
+                    if (e.getStatusCode() == GoogleSignInStatusCodes.SIGN_IN_CANCELLED) {
+                        // cancelled
```
Comment (sonusourav) [inline app/src/main/java/com/iitdh/sonusourav/instigo/Account/LoginActivity.java:319]: Looks fine to me. Just remove the redundant comments and squash your commits in the last.
